module.exports = {
    heads:[
        '排名',
        '姓名',
        '积分',
        '人头数'
    ],
    users:[
        {
            name:'tom',
            points:'35',
            head:'65'
        },
        {
            name:'jenny',
            points:'33',
            head:'10'
        },
        {
            name:'jimmy',
            points:'30',
            head:'10'
        },
        {
            name:'jack',
            points:'30',
            head:'11'
        },
        {
            name:'conney',
            points:'25',
            head:'13'
        },
        {
            name:'wenlong',
            points:'99',
            head:'13'
        },
        {
            name:'wurh',
            points:'101',
            head:'13'
        },
        {
            name:'dad',
            points:'22',
            head:'6'
        }
    ]
}