module.exports = {
    heads:[
        '排名',
        '姓名',
        '积分',
        '人头数'
    ],
    users:[
        {
            name:'郑炜飚',
            points:'5',
            head:'2'
        },
        {
            name:'关智梁',
            points:'6',
            head:'0'
        },
        {
            name:'陈韩杰',
            points:'4',
            head:'0'
        },
        {
            name:'苏晓',
            points:'4',
            head:'1'
        },
        {
            name:'储杰',
            points:'8',
            head:'3'
        },
        {
            name:'杨硕',
            points:'6',
            head:'0'
        },
        {
            name:'李炳津',
            points:'8',
            head:'0'
        },
        {
            name:'郭嘉林',
            points:'5',
            head:'1'
        },
        {
            name:'何妮',
            points:'2',
            head:'0'
        },
        {
            name:'谢玄亮',
            points:'4',
            head:'0'
        },
        {
            name:'don',
            points:'4',
            head:'1'
        },
        {
            name:'吴诗伟',
            points:'2',
            head:'0'
        },
        {
            name:'罗芬',
            points:'4',
            head:'0'
        },
        {
            name:'姜淦',
            points:'2',
            head:'0'
        },
        {
            name:'张冬萌',
            points:'6',
            head:'1'
        },
        {
            name:'陈育文',
            points:'8',
            head:'1'
        },
        {
            name:'周波',
            points:'6',
            head:'1'
        },
        {
            name:'林子杰',
            points:'4',
            head:'0'
        },
        {
            name:'胡慧贤',
            points:'4',
            head:'0'
        },
        {
            name:'施中柱',
            points:'4',
            head:'0'
        },
        {
            name:'李景超',
            points:'7',
            head:'5'
        },
        {
            name:'吴岳',
            points:'4',
            head:'2'
        },
        {
            name:'吴荣恩',
            points:'8',
            head:'0'
        },
        {
            name:'陈旭龙',
            points:'2',
            head:'0'
        },
        {
            name:'子文',
            points:'10',
            head:'2'
        },
        {
            name:'陈南蓓',
            points:'4',
            head:'1'
        },
        {
            name:'何炜华',
            points:'6',
            head:'0'
        },
        {
            name:'李梦宜',
            points:'7',
            head:'1'
        },
        {
            name:'谢瑛',
            points:'4',
            head:'3'
        },
        {
            name:'周慧能',
            points:'4',
            head:'1'
        },
        {
            name:'吴荣华',
            points:'13',
            head:'7'
        },
        {
            name:'买买提',
            points:'9',
            head:'3'
        },
        {
            name:'曾帆',
            points:'9',
            head:'1'
        },
        {
            name:'李宇钧',
            points:'6',
            head:'1'
        },
        {
            name:'钱汝锋',
            points:'4',
            head:'0'
        },
        {
            name:'刘永健',
            points:'4',
            head:'1'
        },
        {
            name:'刘洋',
            points:'7',
            head:'1'
        },
        {
            name:'谢维邦',
            points:'5',
            head:'4'
        },
        {
            name:'易晓键',
            points:'11',
            head:'4'
        },
        {
            name:'陈欣欣',
            points:'8',
            head:'0'
        }
    ]
}